// Auto-generated by: npm run gen:types
// Run after every migration: supabase gen types typescript --local > shared/types/supabase.ts
// Then copy to all apps: npm run gen:types

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          phone: string
          name: string | null
          avatar_url: string | null
          role: 'seller' | 'buyer' | 'admin'
          is_admin: boolean
          loyalty_coins: number
          referral_code: string | null
          referred_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      stores: {
        Row: {
          id: string
          seller_id: string
          store_name: string
          store_slug: string
          description: string | null
          category: 'food' | 'jewellery' | 'clothing' | 'electronics' | 'home' | 'beauty' | 'other'
          logo_url: string | null
          city: string
          area: string | null
          pincode: string | null
          whatsapp_number: string | null
          instagram_handle: string | null
          is_active: boolean
          is_open: boolean
          open_time: string
          close_time: string
          open_days: string[]
          rating_avg: number
          total_reviews: number
          total_orders: number
          is_verified: boolean
          aadhaar_url: string | null
          referral_installs: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['stores']['Row'], 'id' | 'created_at' | 'updated_at' | 'rating_avg' | 'total_reviews' | 'total_orders' | 'referral_installs'>
        Update: Partial<Database['public']['Tables']['stores']['Insert']>
      }
      products: {
        Row: {
          id: string
          store_id: string
          name: string
          description: string | null
          price: number
          compare_price: number | null
          images: string[]
          category: string | null
          is_available: boolean
          stock_type: 'unlimited' | 'counted'
          stock_count: number
          low_stock_threshold: number
          sort_order: number
          total_sold: number
          search_vector: unknown | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at' | 'search_vector' | 'total_sold'>
        Update: Partial<Database['public']['Tables']['products']['Insert']>
      }
      product_variants: {
        Row: {
          id: string
          product_id: string
          variant_type: 'size' | 'color' | 'flavor' | 'weight' | 'other'
          name: string
          price_adjustment: number
          stock_count: number
          is_available: boolean
          sort_order: number
        }
        Insert: Omit<Database['public']['Tables']['product_variants']['Row'], 'id'>
        Update: Partial<Database['public']['Tables']['product_variants']['Insert']>
      }
      orders: {
        Row: {
          id: string
          order_number: string
          store_id: string
          buyer_id: string
          status: 'pending' | 'accepted' | 'rejected' | 'packed' | 'shipped' | 'delivered' | 'cancelled' | 'return_requested' | 'returned'
          payment_status: 'pending' | 'paid' | 'refunded' | 'failed'
          payment_method: 'online' | 'cod'
          razorpay_order_id: string | null
          razorpay_payment_id: string | null
          items: Json
          subtotal: number
          delivery_fee: number
          discount_amount: number
          coins_redeemed: number
          coins_discount: number
          total_amount: number
          delivery_address: Json
          shiprocket_order_id: string | null
          tracking_url: string | null
          awb_code: string | null
          rejection_reason: string | null
          accepted_at: string | null
          shipped_at: string | null
          delivered_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'order_number' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['orders']['Insert']>
      }
      reviews: {
        Row: {
          id: string
          store_id: string
          product_id: string | null
          order_id: string
          buyer_id: string
          rating: number
          review_text: string | null
          photos: string[]
          seller_reply: string | null
          seller_replied_at: string | null
          is_verified_purchase: boolean
          coins_awarded: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['reviews']['Insert']>
      }
      bank_accounts: {
        Row: {
          id: string
          seller_id: string
          account_holder: string
          account_number: string
          ifsc_code: string
          bank_name: string | null
          is_verified: boolean
          razorpay_contact_id: string | null
          razorpay_fund_account_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['bank_accounts']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['bank_accounts']['Insert']>
      }
      payouts: {
        Row: {
          id: string
          seller_id: string
          amount: number
          status: 'pending' | 'processing' | 'done' | 'failed'
          razorpay_payout_id: string | null
          period_start: string | null
          period_end: string | null
          order_count: number
          created_at: string
          processed_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['payouts']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['payouts']['Insert']>
      }
      device_tokens: {
        Row: {
          id: string
          user_id: string
          token: string
          platform: 'ios' | 'android' | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['device_tokens']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['device_tokens']['Insert']>
      }
      notification_preferences: {
        Row: {
          user_id: string
          new_order_push: boolean
          new_order_whatsapp: boolean
          order_update_push: boolean
          order_update_whatsapp: boolean
          promotions_push: boolean
          auto_accept_orders: boolean
        }
        Insert: Database['public']['Tables']['notification_preferences']['Row']
        Update: Partial<Database['public']['Tables']['notification_preferences']['Insert']>
      }
      addresses: {
        Row: {
          id: string
          user_id: string
          label: string
          name: string
          phone: string
          line1: string
          line2: string | null
          area: string | null
          city: string
          state: string
          pincode: string
          is_default: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['addresses']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['addresses']['Insert']>
      }
      wishlists: {
        Row: { user_id: string; product_id: string; created_at: string }
        Insert: Omit<Database['public']['Tables']['wishlists']['Row'], 'created_at'>
        Update: never
      }
      cart_items: {
        Row: {
          id: string
          user_id: string
          store_id: string
          product_id: string
          variant_id: string | null
          quantity: number
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['cart_items']['Row'], 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['cart_items']['Insert']>
      }
      coin_transactions: {
        Row: {
          id: string
          user_id: string
          coins: number
          reason: string
          order_id: string | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['coin_transactions']['Row'], 'id' | 'created_at'>
        Update: never
      }
      coupons: {
        Row: {
          id: string
          store_id: string
          code: string
          type: 'percent' | 'fixed'
          value: number
          min_order_amount: number
          max_discount: number | null
          max_uses: number | null
          per_user_limit: number
          total_uses: number
          valid_from: string
          valid_until: string | null
          is_active: boolean
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['coupons']['Row'], 'id' | 'created_at' | 'total_uses'>
        Update: Partial<Database['public']['Tables']['coupons']['Insert']>
      }
      coupon_uses: {
        Row: {
          id: string
          coupon_id: string
          order_id: string
          buyer_id: string
          discount_amount: number | null
          used_at: string
        }
        Insert: Omit<Database['public']['Tables']['coupon_uses']['Row'], 'id' | 'used_at'>
        Update: never
      }
      broadcasts: {
        Row: {
          id: string
          store_id: string
          message: string
          recipient_count: number
          sent_at: string
          status: 'pending' | 'sent' | 'failed'
        }
        Insert: Omit<Database['public']['Tables']['broadcasts']['Row'], 'id' | 'sent_at'>
        Update: Partial<Database['public']['Tables']['broadcasts']['Insert']>
      }
      returns: {
        Row: {
          id: string
          order_id: string
          buyer_id: string
          store_id: string
          reason: string
          photos: string[]
          status: 'pending' | 'approved' | 'rejected' | 'refunded'
          admin_notes: string | null
          refund_amount: number | null
          razorpay_refund_id: string | null
          requested_at: string
          resolved_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['returns']['Row'], 'id' | 'requested_at'>
        Update: Partial<Database['public']['Tables']['returns']['Insert']>
      }
      followed_stores: {
        Row: { buyer_id: string; store_id: string; created_at: string }
        Insert: Omit<Database['public']['Tables']['followed_stores']['Row'], 'created_at'>
        Update: never
      }
      platform_settings: {
        Row: { key: string; value: Json; updated_by: string | null; updated_at: string }
        Insert: Database['public']['Tables']['platform_settings']['Row']
        Update: Partial<Database['public']['Tables']['platform_settings']['Insert']>
      }
      announcements: {
        Row: {
          id: string
          title: string
          message: string
          target: 'all' | 'sellers' | 'buyers'
          is_active: boolean
          created_by: string | null
          created_at: string
          expires_at: string | null
        }
        Insert: Omit<Database['public']['Tables']['announcements']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['announcements']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: {
      add_loyalty_coins: {
        Args: { p_user_id: string; p_coins: number; p_reason: string; p_order_id?: string }
        Returns: void
      }
      redeem_loyalty_coins: {
        Args: { p_user_id: string; p_coins: number; p_order_id: string }
        Returns: number
      }
      use_coupon: {
        Args: { p_coupon_id: string; p_order_id: string; p_buyer_id: string; p_discount: number }
        Returns: void
      }
      generate_store_slug: {
        Args: { store_name: string }
        Returns: string
      }
    }
    Enums: Record<string, never>
  }
}
